export default {
    background: require('../assets/shopping1_1.jpeg'),
    shoppingBanner: require('../assets/Ishopping.png'),
    shoppingBanner1: require('../assets/Ishopping2.png'),

    thoiTrangNam : require('../assets/imgProductList/ThoiTrangNam.jpeg' ),
    thoiTrangNu: require('../assets/imgProductList/ThoiTrangNu.jpeg' ),
    dienThoai : require('../assets/imgProductList/DienThoai.jpeg' ),
    dongHo:require('../assets/imgProductList/DongHo.jpeg' ) ,
    giayDepNu:  require('../assets/imgProductList/GiayDepNu.jpeg' ), 
    giayDepNam: require('../assets/imgProductList/GiayDepNam.jpeg' ),
    mayAnh: require('../assets/imgProductList/MayAnh.jpeg' ), 
    mayTinh: require('../assets/imgProductList/MayTinh.jpeg' ),
    meVaBe: require('../assets/imgProductList/MeVaBe.jpeg' ), 
    nhaCua: require('../assets/imgProductList/NhaCua.jpeg' ), 
    nhaSachOnline: require('../assets/imgProductList/NhaSachOnline.jpeg' ), 
    OTo: require('../assets/imgProductList/OTo.jpeg' ), 
    phuKienTrangSucNu: require('../assets/imgProductList/PhuKienTrangSucNu.jpeg' ), 
    sacDep: require('../assets/imgProductList/SacDep.jpeg' ), 
    theThao: require('../assets/imgProductList/TheThao.jpeg' ), 
     thietBiDienGiaDung: require('../assets/imgProductList/ThietBiDienGiaDung.jpeg' ), 
     thietBiDienTu: require('../assets/imgProductList/ThietBiDienTu.jpeg' ), 
     tuiViNu:require('../assets/imgProductList/TuiViNu.jpeg' ), 
     sucKhoe: require('../assets/imgProductList/SucKhoe.jpeg'),
     bachHoaOnline : require('../assets/imgProductList/BachHoaOnline.jpeg'),
     traSua: require('../assets/imgProductList/traSua.png'),

     iphone13 : require('../assets/imgProduct/m9.jpeg'),
     macbook: require('../assets/imgProduct/m32.jpeg') ,
     tablet: require('../assets/imgProduct/m1.jpeg'), 
     vestNam: require('../assets/imgProduct/n1.jpeg'),
     soMiNam: require('../assets/imgProduct/n10.jpeg'),
     aoPhongNam: require('../assets/imgProduct/n11.jpeg'), 
     dauGoiDau: require('../assets/imgProduct/d2.jpeg'),
     suaTam: require('../assets/imgProduct/d4.jpeg'), 
     soMiNu:require('../assets/imgProduct/g7.jpeg') , 
     vayNu: require('../assets/imgProduct/g1.jpeg'), 
     chanVayNu: require('../assets/imgProduct/v5.jpeg'),
     kepToc: require('../assets/imgProduct/p1.jpeg'), 
     khanTam: require('../assets/imgProduct/p8.jpeg'), 


    barbecue: require('../assets/imgProductFood/barbecue.jpeg'), 
    bbq:require('../assets/imgProductFood/bbq.jpeg') , 
    beverages: require('../assets/imgProductFood/beverages.jpeg'), 
    breakfast: require('../assets/imgProductFood/breakfast.jpeg'), 
    coffee: require('../assets/imgProductFood/coffee.jpeg'), 
    desert: require('../assets/imgProductFood/desert.jpeg'), 
    dinner: require('../assets/imgProductFood/dinner.webp'), 
    hotdog: require('../assets/imgProductFood/hodog.jpeg'), 
    noodles: require('../assets/imgProductFood/noodles.jpeg'), 
    wine: require('../assets/imgProductFood/wine.jpeg'), 

    
    foodBanhKem: require('../assets/imgFoodItem/banhKem.jpeg'),
    foodBanhRanDuong: require('../assets/imgFoodItem/banhRanDuong.jpeg'),
    foodBanhChung: require('../assets/imgFoodItem/banhTrung.jpeg'),
    foodBapLuoc: require('../assets/imgFoodItem/bapLuoc.jpeg'),
    foodRauLuoc: require('../assets/imgFoodItem/rauLuoc.jpeg'),
    foodThitGaluoc: require('../assets/imgFoodItem/thitGa.jpeg'),
    foodThitGaHap: require('../assets/imgFoodItem/thitGa1.jpeg'),
    foodWineVang: require('../assets/imgFoodItem/wineVang.jpeg'),
    foodCoca: require('../assets/imgFoodItem/coca.jpeg'),
    foodSprite: require('../assets/imgFoodItem/sprite.jpeg'),
    foodNuocCam: require('../assets/imgFoodItem/nuocCam.jpeg'),
    foodNuocHoaQua: require('../assets/imgFoodItem/nuocHoaQua.jpeg'),

    giCungRe: require('../assets//imgProductDes/giCungRe1.jpeg'),
    themVaoCart: require('../assets//imgProductDes/themVaoCart.png'),

    freeShip: require('../assets/imgCart/freeship.png'),
    freeShip1: require('../assets/imgCart/freeShip.jpeg'),


}